### ISSUE TITLE
The encoded image detection model 

### ISSUE THREAD

**Issue by zcx-language** [FangHanNUS/MM22_PIMoG#1]
Thanks for your excellent work on screen-shooting resilient watermarking.

In this paper:

> the detection and correction process of watermarked images are the same as the settings of StegaStamp. 

So could you share the pre-trained segmentation model for testing?

**Comment by FangHanNUS** [comment]
Thank you for paying attention to our work. The detection model of Stegastamp has been open-sourced at their github: https://github.com/tancik/StegaStamp. You can download and try it. Besides, we have open-sourced a perspective transformation version with handcrafted locating in this project (see PerspectiveTransformation), you could also have a try.

**Comment by zcx-language** [comment]
I see, thanks for your reply.
By the way, I am pursuing a Ph.D. in Hust,  and recently I wonder whether there exists a universal segmentation model that can be used to locate the watermarked region in different watermarking systems, similar to steganalysis. I have shared my WeChat number via email, with the hope of not causing any inconvenience, and eagerly anticipate further discussions with you on this topic.
